version: '3.9'
services:
  mongo:
    container_name: mongo
    image: mongo:3.6
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
  redis:
    container_name: redis
    image: redis:5-alpine
    ports:
      - 6379:6379
  mysql:
    container_name: mysql
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
volumes:
  mongo:
  mysql: